#!/bin/bash

INNOSETUP="setup_dragonsphere.exe"

if [ ! -f $INNOSETUP ]; then
  echo "ERROR: The setup file ($INNOSETUP) wasn't found."
  echo "Make sure you downloaded it from your GOG account, then run this installer from the same directory."
  exit 1
fi

INSTALL_DIR="dragonsphere-gog"

if [ -d $INSTALL_DIR ]; then
  echo "ERROR: The directory '$INSTALL_DIR' already exists; aborting to prevent overwriting your files."
  exit 1
fi

echo "Installing Dragonsphere into '$INSTALL_DIR'..."

mkdir -p $INSTALL_DIR
mkdir -p $INSTALL_DIR/docs

mkdir -p $GOG_TMP_DIR
cd $GOG_TMP_DIR

innoextract --silent ../$INNOSETUP

# Moving only the interesting files
mv app/answers.txt ../$INSTALL_DIR/docs
mv app/manual.pdf ../$INSTALL_DIR/docs
mv app/DRAGON ../$INSTALL_DIR
mv app/GAME.GOG ../$INSTALL_DIR
mv app/GAME.INST ../$INSTALL_DIR
mv app/gfw_high.ico ../$INSTALL_DIR
mv tmp/gog_EULA.txt ../$INSTALL_DIR
# WTF?
mv tmp/default/default/default/default/dosboxDragonsphere.conf ../$INSTALL_DIR/dosbox.conf

cd ..
rm -rf $GOG_TMP_DIR

# A few quick fixes from the forum
sed -i '197s/.*/call DRAGON.BAT/' $INSTALL_DIR/dosbox.conf
sed -i '65s/.*/core=auto/' $INSTALL_DIR/dosbox.conf

echo "Done!"
echo "To run, enter '$INSTALL_DIR' and type 'dosbox' (dosbox.conf will take care of the rest)."
echo "OBS.: The game is self-contained; you can move/rename '$INSTALL_DIR' if you want."
