#!/usr/bin/env bash
#
# Copyright 2012 Rafael Martins
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ "$1" == "" ]; then
  echo "gog-installer: No game or option specified."
  echo "Try 'gog-installer --help' for more information."
  exit 1
fi

if [ "$1" == "--help" ]; then
  echo "Usage: gog-installer [OPTIONS] SETUP_FILE"
  echo "Installs a game downloaded from GOG.com."
  echo ""
  echo "Options:"
  echo "      --help      display this help and exit"
  exit 0
fi

if [[ $1 == --* ]]; then
  echo "gog-installer: unrecognized option '$1'"
  echo "Try 'gog-installer --help' for more information."
  exit 1
fi

# Checking global prerequisites
if ! which innoextract >/dev/null; then
  echo "ERROR: The command 'innoextract' wasn't found. Check [https://github.com/dscharrer/InnoExtract/]." 
  exit 1
fi

GOG_TMP_DIR="/tmp/gog-installer_$(whoami)"

SETUP=$1

if [ ! -f $SETUP ]; then
  echo "ERROR: The game setup file ('$SETUP') wasn't found."
  exit 1
fi

GAME=`echo $1 | sed 's/setup_\(.*\).exe/\1/'`
if [ "$GAME" == "" ] || [ "$GAME" == "$SETUP" ]; then
  echo "ERROR: Couldn't determine the game's name from the setup file. Recognized names are in the format 'setup_<name[_version]>.exe'."
  exit 1
fi

INSTALL_DIR="$(pwd)/$GAME"
if [ -d $INSTALL_DIR ]; then
  echo "ERROR: The directory '$INSTALL_DIR' already exists; aborting to prevent overwriting your files."
  exit 1
fi
if ! mkdir -p $INSTALL_DIR 2>/dev/null; then
  echo "ERROR: Couldn't create directory '$INSTALL_DIR'. Check your permissions."
  exit 1
fi

echo "Installing $GAME into '$INSTALL_DIR'..."

if ! mkdir -p $GOG_TMP_DIR 2>/dev/null; then
  echo "ERROR: Couldn't create temp dir ($GOG_TMP_DIR). Check your permissions."
  exit 1
fi

SETUP_FULL=$(readlink -f $SETUP)

cd $GOG_TMP_DIR

innoextract $SETUP_FULL

cp app/* $INSTALL_DIR -rf
rm $INSTALL_DIR/goggame.dll
rm $INSTALL_DIR/Support.ico
rm $INSTALL_DIR/innosetup_license.txt

# Checking for dosbox.conf
TMP_DEFAULT=$GOG_TMP_DIR/tmp/default/default/default/default
if [ -d $TMP_DEFAULT ]; then
  cp $TMP_DEFAULT/* $INSTALL_DIR -rf
fi

cp tmp/gog_EULA.txt $INSTALL_DIR -rf
less $INSTALL_DIR/gog_EULA.txt

# final clean
cd 
rm -rf $GOG_TMP_DIR
echo "Success! The game was repackaged into '$INSTALL_DIR'."
exit 0

echo "gog-installer: game '$1' isn't supported (or doesn't exist)."
exit 1
